// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ingredients.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createIngredient = `-- name: CreateIngredient :one
INSERT INTO ingredients (id, name, image_key, created_at, updated_at)
VALUES (
	gen_random_uuid(),
	$1,
	$2,
	NOW(),
	NOW()
) RETURNING id, name, image_key, created_at, updated_at
`

type CreateIngredientParams struct {
	Name     string
	ImageKey string
}

func (q *Queries) CreateIngredient(ctx context.Context, arg CreateIngredientParams) (Ingredient, error) {
	row := q.db.QueryRowContext(ctx, createIngredient, arg.Name, arg.ImageKey)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ImageKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIngredients = `-- name: GetIngredients :many
SELECT id, name FROM ingredients
`

type GetIngredientsRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) GetIngredients(ctx context.Context) ([]GetIngredientsRow, error) {
	rows, err := q.db.QueryContext(ctx, getIngredients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetIngredientsRow
	for rows.Next() {
		var i GetIngredientsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
