// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ingredients.sql

package database

import (
	"context"
)

const createIngredient = `-- name: CreateIngredient :one
INSERT INTO ingredients (id, name, image_key, created_at, updated_at)
VALUES (
	gen_random_uuid(),
	$1,
	$2,
	NOW(),
	NOW()
) RETURNING id, name, image_key, created_at, updated_at
`

type CreateIngredientParams struct {
	Name     string
	ImageKey string
}

func (q *Queries) CreateIngredient(ctx context.Context, arg CreateIngredientParams) (Ingredient, error) {
	row := q.db.QueryRowContext(ctx, createIngredient, arg.Name, arg.ImageKey)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ImageKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
