// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ingredients.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createIngredient = `-- name: CreateIngredient :one
INSERT INTO ingredients (id, name, quantity, unit, created_at, updated_at, recipe_id)
VALUES (
	gen_random_uuid(),
	$1,
	$2,
	$3,
	NOW(),
	NOW(),
	$4
) RETURNING id, name, quantity, unit, created_at, updated_at, recipe_id
`

type CreateIngredientParams struct {
	Name     string
	Quantity float32
	Unit     string
	RecipeID uuid.UUID
}

func (q *Queries) CreateIngredient(ctx context.Context, arg CreateIngredientParams) (Ingredient, error) {
	row := q.db.QueryRowContext(ctx, createIngredient,
		arg.Name,
		arg.Quantity,
		arg.Unit,
		arg.RecipeID,
	)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Quantity,
		&i.Unit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RecipeID,
	)
	return i, err
}
