// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Ingredient struct {
	ID        uuid.UUID
	Name      string
	Quantity  float32
	Unit      string
	CreatedAt time.Time
	UpdatedAt time.Time
	RecipeID  uuid.UUID
}

type Recipe struct {
	ID          uuid.UUID
	Title       string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	UserID      uuid.UUID
	Description string
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
	HashedPw  string
	Name      string
}
