// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recipeIngredients.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addToRecipe = `-- name: AddToRecipe :one
INSERT INTO recipe_ingredients (recipe_id, ingredient_id, quantity, unit)
VALUES (
	$1,
	$2,
	$3,
	$4
) RETURNING recipe_id, ingredient_id, quantity, unit
`

type AddToRecipeParams struct {
	RecipeID     uuid.UUID
	IngredientID uuid.UUID
	Quantity     float32
	Unit         string
}

func (q *Queries) AddToRecipe(ctx context.Context, arg AddToRecipeParams) (RecipeIngredient, error) {
	row := q.db.QueryRowContext(ctx, addToRecipe,
		arg.RecipeID,
		arg.IngredientID,
		arg.Quantity,
		arg.Unit,
	)
	var i RecipeIngredient
	err := row.Scan(
		&i.RecipeID,
		&i.IngredientID,
		&i.Quantity,
		&i.Unit,
	)
	return i, err
}

const getIngredientList = `-- name: GetIngredientList :many
SELECT id, name, image_key, created_at, updated_at, recipe_id, ingredient_id, quantity, unit FROM ingredients
INNER JOIN recipe_ingredients ON ingredients.id = recipe_ingredients.ingredient_id
WHERE recipe_ingredients.recipe_id = $1
`

type GetIngredientListRow struct {
	ID           uuid.UUID
	Name         string
	ImageKey     string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	RecipeID     uuid.UUID
	IngredientID uuid.UUID
	Quantity     float32
	Unit         string
}

func (q *Queries) GetIngredientList(ctx context.Context, recipeID uuid.UUID) ([]GetIngredientListRow, error) {
	rows, err := q.db.QueryContext(ctx, getIngredientList, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetIngredientListRow
	for rows.Next() {
		var i GetIngredientListRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ImageKey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RecipeID,
			&i.IngredientID,
			&i.Quantity,
			&i.Unit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecipesIngredients = `-- name: GetRecipesIngredients :many
SELECT ingredient_id FROM recipe_ingredients
WHERE recipe_id = $1
`

func (q *Queries) GetRecipesIngredients(ctx context.Context, recipeID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getRecipesIngredients, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var ingredient_id uuid.UUID
		if err := rows.Scan(&ingredient_id); err != nil {
			return nil, err
		}
		items = append(items, ingredient_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
