// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recipes.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createRecipe = `-- name: CreateRecipe :one
INSERT INTO recipes (id, created_at, updated_at, user_id)
VALUES(
	gen_random_uuid(),
	NOW(),
	NOW(),
	$1
)
RETURNING id, created_at, updated_at, user_id
`

func (q *Queries) CreateRecipe(ctx context.Context, userID uuid.UUID) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, createRecipe, userID)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}
