// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shoppingLists.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createShoppingList = `-- name: CreateShoppingList :one
INSERT INTO shopping_lists (id, name, created_at, updated_at, user_id)
VALUES (
	gen_random_uuid(),
	$1,
	NOW(),
	NOW(),
	$2
) RETURNING id, name, created_at, updated_at, user_id
`

type CreateShoppingListParams struct {
	Name   string
	UserID uuid.UUID
}

func (q *Queries) CreateShoppingList(ctx context.Context, arg CreateShoppingListParams) (ShoppingList, error) {
	row := q.db.QueryRowContext(ctx, createShoppingList, arg.Name, arg.UserID)
	var i ShoppingList
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}
