// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: units.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createConversion = `-- name: CreateConversion :exec
INSERT INTO conversions (ingredient_id, from_unit, to_unit, ratio)
VALUES (
	$1,
	$2,
	$3,
	$4
)
`

type CreateConversionParams struct {
	IngredientID uuid.UUID
	FromUnit     string
	ToUnit       string
	Ratio        float32
}

func (q *Queries) CreateConversion(ctx context.Context, arg CreateConversionParams) error {
	_, err := q.db.ExecContext(ctx, createConversion,
		arg.IngredientID,
		arg.FromUnit,
		arg.ToUnit,
		arg.Ratio,
	)
	return err
}
