// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: units.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createConversion = `-- name: CreateConversion :exec
INSERT INTO conversions (ingredient_id, from_unit, to_unit, ratio)
VALUES (
	$1,
	$2,
	$3,
	$4
)
`

type CreateConversionParams struct {
	IngredientID uuid.UUID
	FromUnit     string
	ToUnit       string
	Ratio        float32
}

func (q *Queries) CreateConversion(ctx context.Context, arg CreateConversionParams) error {
	_, err := q.db.ExecContext(ctx, createConversion,
		arg.IngredientID,
		arg.FromUnit,
		arg.ToUnit,
		arg.Ratio,
	)
	return err
}

const getConversionsByID = `-- name: GetConversionsByID :many
SELECT ingredient_id, from_unit, to_unit, ratio FROM conversions
WHERE ingredient_id = $1
`

func (q *Queries) GetConversionsByID(ctx context.Context, ingredientID uuid.UUID) ([]Conversion, error) {
	rows, err := q.db.QueryContext(ctx, getConversionsByID, ingredientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversion
	for rows.Next() {
		var i Conversion
		if err := rows.Scan(
			&i.IngredientID,
			&i.FromUnit,
			&i.ToUnit,
			&i.Ratio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
