// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, email, hashed_pw)
VALUES (
	gen_random_uuid(),
	NOW(),
	NOW(),
	$1,
	$2
) RETURNING id, created_at, email
`

type CreateUserParams struct {
	Email    string
	HashedPw string
}

type CreateUserRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	Email     string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.HashedPw)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.Email)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, created_at, updated_at, email FROM USERS
WHERE id = $1
`

type GetUserRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
}

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
	)
	return i, err
}

const getUserHash = `-- name: GetUserHash :one
SELECT id, hashed_pw FROM users
WHERE email = $1
`

type GetUserHashRow struct {
	ID       uuid.UUID
	HashedPw string
}

func (q *Queries) GetUserHash(ctx context.Context, email string) (GetUserHashRow, error) {
	row := q.db.QueryRowContext(ctx, getUserHash, email)
	var i GetUserHashRow
	err := row.Scan(&i.ID, &i.HashedPw)
	return i, err
}

const resetUsers = `-- name: ResetUsers :exec
DELETE FROM users
`

func (q *Queries) ResetUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetUsers)
	return err
}
