// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, email, hashed_pw)
VALUES (
	$1,
	NOW(),
	NOW(),
	$2,
	$3
) RETURNING id, created_at, email
`

type CreateUserParams struct {
	ID       uuid.UUID
	Email    string
	HashedPw string
}

type CreateUserRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	Email     string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.ID, arg.Email, arg.HashedPw)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.Email)
	return i, err
}
