-- +goose Up
INSERT INTO units (name, abbreviation) VALUES 
('Teaspoon', 'tsp'),
('Tablespoon', 'tbsp'),
('Cup', 'c'),
('Fluid Ounce', 'fl oz'),
('Ounce', 'oz'),
('Pound', 'lb'),
('Gram', 'g'),
('Kilogram', 'kg'),
('Milliliter', 'ml'),
('Liter', 'l'),
('Count', 'qty'),
('Pinch', 'pn'),
('Dash', 'ds'),
('Clove', 'clv'),
('Stick', 'stk'),
('Packet', 'pkt');

INSERT INTO retail_units (name) VALUES 
-- Dairy & Refrigerated
('Stick'),
('Carton (12ct)'),
('Carton (16oz)'),
('Carton (32oz)'),
('Carton (52oz)'),
('Container (6oz)'),
('Container (8oz)'),
('Container (15oz)'),
('Container (16oz)'),
('Container (32oz)'),
('Block (8oz)'),
('Block (14oz)'),
('Log (4oz)'),
('Wedge (8oz)'),

-- Pantry & Baking
('Bag (1lb)'),
('Bag (2lb)'),
('Bag (4lb)'),
('Bag (5lb)'),
('Box (1lb)'),
('Box (3lb)'),
('Box (4oz)'),
('Box (8oz)'),
('Bottle (2oz)'),
('Bottle (5oz)'),
('Bottle (6oz)'),
('Bottle (10oz)'),
('Bottle (12oz)'),
('Bottle (16oz)'),
('Bottle (17oz)'),
('Bottle (48oz)'),
('Bottle (64oz)'),
('Jar (0.5oz)'),
('Jar (0.7oz)'),
('Jar (1.5oz)'),
('Jar (1.8oz)'),
('Jar (2oz)'),
('Jar (2.3oz)'),
('Jar (3oz)'),
('Jar (3.5oz)'),
('Jar (4oz)'),
('Jar (6oz)'),
('Jar (8oz)'),
('Jar (12oz)'),
('Jar (16oz)'),
('Jar (30oz)'),
('Can (6oz)'),
('Can (8oz)'),
('Can (10.75oz)'),
('Can (12oz)'),
('Can (13.5oz)'),
('Can (14oz)'),
('Can (14.5oz)'),
('Can (15oz)'),
('Can (16oz)'),
('Canister (8oz)'),
('Canister (15oz)'),
('Canister (18oz)'),
('Packet (0.25oz)'),

-- Produce
('Count'),
('Head'),
('Bunch'),
('Root'),
('Pint'),
('Quart'),
('Pack (0.75oz)'),
('Pack (16oz)'),

-- Meats & Frozen
('Pack (1lb)'),
('Pack (1.5lb)'),
('Pack (19oz)'),
('Pack (8oz)'),
('Pack (4oz)'),
('Pack (4ct)'),
('Unit (5lb)'),
('Bag (24oz)'),
('Bag (20oz)'),
('Bag (8oz)'),
('Bag (2oz)'),
('Bag (10oz)'),
('Bag (12oz)'),
('Gallon'),

-- Misc
('Ball (8oz)'),
('Bottle (16.9oz)'),
('Bottle (20oz)'),
('Bottle (500ml)');


-- +goose Down
DELETE FROM conversions; DELETE FROM units; DELETE FROM retail_units;
